### ISSUE TITLE
Auto-tune the dynamic cut parameter

### ISSUE THREAD

**Issue by jacobbien** [andeek/protoshiny#16]
Try a grid of dynamic cut parameter values to find one that leads to a good number of nodes being shown in the initial layout.  Probably want 20-30 visible nodes?

**Comment by andeek** [comment]
Dynamic cut tree not currently affecting the visualization

**Comment by andeek** [comment]
This has been addressed in https://github.com/andeek/protoshiny/commit/8881bc9d2914fca858eb776160d560fcb44f58e5. Need to add now a sentence uner the selection box with our suggestion and a better default value. Also, bold the table value we like (closest to 50?).
