### ISSUE TITLE
Descendants whose heights are close to their ancestors' heights

### ISSUE THREAD

**Issue by jacobbien** [andeek/protoshiny#2]
This may be common in large trees.  See, e.g., the preloaded words example.  The nodes closest to the root are all extremely similar to each other, so visually the tree structure is not apparent.  Zooming might fix this or applying some monotonic transformation to the heights.

**Comment by andeek** [comment]
See new zoom function from https://github.com/andeek/protoshiny/commit/1d161426aa6969c6b5a9e2e75fe31ccad0508d08
