### ISSUE TITLE
Search for label

### ISSUE THREAD

**Issue by jacobbien** [andeek/protoshiny#3]
User types in label and presses "Search".  It expands tree showing the path from root to the first occurrence of this label.  Here "first occurrence" means that it finds the node closest to the root that has that label.  Sometimes this node will be a leaf, in which case we can see all the ancestor prototypes of this node.  Otherwise, it will be showing the largest cluster that has this label as prototype.

**Comment by jacobbien** [comment]
I've added to the protoclust package the function find_elements (see commit https://github.com/jacobbien/protoclust/commit/834a042a313d703d9154f46cce3fdd9298518d57).  For most up-to-date version of protoclust, use: devtools::install_github("jacobbien/protoclust")

**Comment by andeek** [comment]
Closed by fc7fbf3d3a76802e58b4d3ca2c887b05673c9f21
